### ISSUE TITLE
The color of the clock does not change for players

### ISSUE THREAD

**Issue by maxpertcev** [CarlosFdez/global-progress-clocks#14] opened 2024-03-25 10:49 UTC
I have set up different colors for different clocks, but my players have them all in red. I am using latest version of module 4.2 and Foundry 11 315 

Mine
![image](https://github.com/CarlosFdez/global-progress-clocks/assets/76617162/dfedf3f8-b71d-4c8c-b7da-64d2c517bc5b)

Players 
![image](https://github.com/CarlosFdez/global-progress-clocks/assets/76617162/6f8cbe29-b1c2-4afa-81b8-9944008bd0af)

**Comment by maxpertcev** [comment] 2024-03-27 09:21
> That's super weird, and its odd it hasn't been reported till now, I'll take a look.

My players thought that this was how it should be, and they didn't say anything. This fact was revealed by chance in general.

**Comment by CarlosFdez** [comment] 2024-03-27 21:04
That would explain it. The issue is that I forgot to make them world settings. I'll fix that today.

**Comment by CarlosFdez** [comment] 2024-03-27 21:35
This should be fixed now in 0.4.3. Feel free to re-open if I messed this up in some way.

**Closed by CarlosFdez** 2024-03-27 21:35 UTC
